store1:
  location: [-1.25, -1]
  type: ""

store2:
  location: [-1, -2]
  type: ""

store3:
  location: [-1, -1.5]
  type: ""

store4:
  location: [-0.75, -0.7]
  type: ""

store5:
  location: [0.75, -1.3]
  type: ""

store6:
  location: [1, -2]
  type: ""

store7:
  location: [1, 1.5]
  type: ""

store8:
  location: [1.25, -1]
  type: ""